### DISCUSSION TITLE
Anyway to get this to work with an ESP32?

### DISCUSSION THREAD

**Discussion by timothylui** [Alexwijn/SAT#50] [General]
I bought this esp32 based opentherm gateway, can I get it to work with this, or do I need to get an ESP8266? 

https://diyless.com/product/opentherm-thermostat

**Comment by sergeantd83** [comment]
We added some initial support for the OpenTherm adapter. @cnrd has a working SAT installation based on this board. If he has some spare time, he can provide some help to get it work. Meanwhile we are waiting for the official OpenTherm ESPHome component to fully support it.

**Comment by cnrd** [comment]
I am unsure of how familiar you are with esphome?

This is the configuration needed to setup opentherm on esphome, you will need to add the usual configuration on top of this, this is just the opentherm parts.

You may also need to update the pins used for communication, I am using an ESP32 S2 mini, but I think the pinout may be different on the ESP32 mini (not sure if you are reflashing the diyless one?)

You should not change the naming of any of the configured entities, they are named as SAT is expecting them.

Be aware that this is not a minimal example, I have added some extra fields that I use.

Let me know if you need more help 😄

```yaml
external_components:
  source: github://olegtarasov/esphome-opentherm@main
  refresh: 0s

opentherm:
  in_pin: 33
  out_pin: 35
  ch_enable: true
  dhw_enable: true

number:
  - platform: opentherm
    t_dhw_set:
      name: "dhw_setpoint_temperature"
      min_value: 30.0
      max_value: 70.0
      step: 1
      initial_value: 55.0
      restore_value: true
    t_set:
      name: "ch_setpoint_temperature"
      min_value: 0.0
      max_value: 80.0
      step: 0.1
      initial_value: 0.0
      restore_value: true
    max_t_set:
      name: "max_ch_setpoint_temperature"
      min_value: 20.0
      max_value: 80.0
      initial_value: 80.0
      step: 1
      restore_value: true
    max_rel_mod_level:
      name: "max_modulation_level"
      entity_category: config
      min_value: 0
      max_value: 100
      step: 1
      initial_value: 100
      restore_value: true

sensor:
  - platform: opentherm
    rel_mod_level:
      name: "modulation"
    device_id:
      name: "boiler_member_id"
    t_boiler:
      name: "boiler_temperature"
    t_ret:
      name: "return_temperature"
    t_dhw_set_lb:
      name: "dhw_min_temperature"
    t_dhw_set_ub:
      name: "dhw_max_temperature"
    t_dhw:
      name: "Hot Water Temperature"
    ch_pressure:
      name: "Heating Water Pressure"
      unit_of_measurement: hPa
    t_exhaust:
      name: "Exhaust temperature"
    max_capacity:
      name: "max_capacity"
    min_mod_level:
      name: "min_mod_level"


binary_sensor:
  - platform: opentherm
    flame_on:
      name: "flame_active"
    ch_active:
      name: "Central Heating active"
    dhw_active:
      name: "Hot Water active"
    fault_indication:
      name: "Boiler Fault indication"
      entity_category: diagnostic
    diagnostic_indication:
      name: "Boiler Diagnostic event"
      entity_category: diagnostic

switch:
  - platform: opentherm
    dhw_enable:
      name: "dhw_enabled"
      restore_mode: RESTORE_DEFAULT_ON
      entity_category: config
    ch_enable:
      name: "ch_enabled"
      restore_mode: RESTORE_DEFAULT_ON
      entity_category: config
```

**Comment by sergeantd83** [comment]
Also you need to run the latest `develop` version in order to achieve connection.

**Reply by Thijssvd** [reply]
Hi, I have the diyless thermostat 2. Can you help with getting SAT on there? Does anyone know which the OT pins are?

**Reply by cnrd** [reply]
Actually [ESPHome 2024.11](https://github.com/esphome/esphome/releases/tag/2024.11.0) was just released two hours ago, so when I have time I will probably do a PR that updates everything to follow the official naming and include an example config.

I think it may be in_pin: 16 out_pin: 17 on the ESP32 mini

**Comment by timothylui** [comment]
Hi thanks for the help, I've got ESPHome up and running with opentherm, how do I install the develop version? It only gives me the following options

![image](https://github.com/user-attachments/assets/9dc3b1fd-477f-403a-8bd5-98b28684935a)

**Comment by timothylui** [comment]
If i try to add manually, i get this error.

![image](https://github.com/user-attachments/assets/d7eeed47-4940-40c6-a973-1110df41aae1)

**Comment by timothylui** [comment]
ignore me, I installed it manually

**Comment by sergeantd83** [comment]
Or download the latest version and then
go to developer tools -> services -> service -> `update.install` -> choose entity -> `update.smart_autotune_thermostat_update` -> check version -> fill `develop` -> call service

**Reply by timothylui** [reply]
ok thanks, that is a better way. I got it all set up, I'll find out tomorrow morning if it's working correctly whether my other half shouts at me that the kitchen is freezing cold...

**Comment by sergeantd83** [comment]
Some initial settings:
If you had an error during the overshoot protection value calculation then reconfigure SAT and manually add the value 50.
In settings -> General
Choose the Precision Curve
Improved controller
Heating Curve: 2
Automatic gains: 2
Derivative time weight: 2.5

**Comment by GravitySandwichh** [comment]
i tried above config but SAT seems to not do anything to the CV. During calibration nothing happens. After the integration is added, the boiler never turns on to heat. 

![image](https://github.com/user-attachments/assets/bff278f8-05f3-45af-ada3-cc725ae2cc56)
![image](https://github.com/user-attachments/assets/d083ada4-d074-44c8-a9bd-788a9062d5b7)
![image](https://github.com/user-attachments/assets/e8160893-141d-4848-ade2-a96dc27923d7)
![image](https://github.com/user-attachments/assets/d73cd90c-ec97-4628-aa05-1e861e662b7a)
![image](https://github.com/user-attachments/assets/40ee5667-d318-4600-a12b-799cedf20a50)

**Comment by GravitySandwichh** [comment]
Got it working with the readme here:
https://github.com/sergeantd83/SAT?tab=readme-ov-file#opentherm

**Comment by ihatethecloud** [comment]
@cnrd 

Hey,
Do you have an updated version of your esphome? Tried it with yours and I get a timeout from sat waiting for the boiler to start during the calibration.

I currently I have the diyless thermostat shield with this config.

```
opentherm:
  in_pin: 4 # WeMos D1 Mini ESP32 input pin for stacking with Master OpenTherm Shield
  out_pin: 5 # WeMos D1 Mini ESP32 output pin for stacking with Master OpenTherm Shield


# Use switches to enable/disable central heating and hot water from HA interface
# https://esphome.io/components/opentherm.html#switch
switch:
  - platform: opentherm
    ch_enable:
      id: ch_enable
      name: "Heating"
      restore_mode: RESTORE_DEFAULT_OFF
      internal: false
    dhw_enable:
      id: dhw_enable
      name: "Hot Water"
      restore_mode: RESTORE_DEFAULT_OFF

# Use outputs to control numerical values like Central Heating setpoint using some automatic algorithms
output:
  - platform: opentherm
    t_set:
      id: ch_setpoint
      min_value: 30
      max_value: 55
      zero_means_zero: true


# Use numbers to control numerical values like CH/DHW setpoint from HA interface
# https://esphome.io/components/opentherm.html#numerical-values 
number:
  - platform: opentherm
    t_dhw_set:
      id: dhw_setpoint
      name: "Hot Water Setpoint"
      step: 1
      min_value: 30
      max_value: 50
      restore_value: true
      initial_value: 45

# Use binary sensors (on/off) to monitor the states and conditions of different boiler entities.
# https://esphome.io/components/opentherm.html#binary-sensor
binary_sensor:
  - platform: opentherm
    ch_active:
      id: ch_active
      name: "Heating Active"
    dhw_active:
      id: dhw_active
      name: "Hot Water Active"
      
    flame_on:
      id: flame_on
      name: "Flame On"
    fault_indication:
      id: fault_indication
      name: "Boiler Fault"
      entity_category: diagnostic
    diagnostic_indication:
      id: diagnostic_indication
      name: "Boiler Diagnostic"
      entity_category: diagnostic
    service_request:
      name: Service Required
      entity_category: diagnostic

    lockout_reset:
      name: Lockout Reset
      entity_category: diagnostic
    low_water_pressure:
      name: Low Water Pressure Fault
      entity_category: diagnostic
    flame_fault:
      name: Flame Fault
      entity_category: diagnostic
    air_pressure_fault:
      name: Air Pressure Fault
      entity_category: diagnostic
    water_over_temp:
      name: Water Overtemperature
      entity_category: diagnostic      




# Enable 1-Wire bus for DS18B20 temperature sensor
one_wire:
  - platform: gpio
    pin: 14 # WeMos D1 Mini ESP32 1-wire pin for stacking with Master OpenTherm Shield

sensor:
# Wired DALLAS DS18B20 sensor
- platform: dallas_temp
  id: dallas_sensor
  name: "Wired Sensor Temperature"
  update_interval: 30s
  accuracy_decimals: 2
  filters:
    - sliding_window_moving_average:
        window_size: 5
        send_every: 2
    - heartbeat: 1s
- platform: homeassistant
  id: current_temperature
  entity_id: sensor.master_bedroom_temperature_temperature

# OpenTherm sensors
# https://esphome.io/components/opentherm.html#sensor
- platform: opentherm
  t_boiler:
    id: ch_temperature
    name: "Heating Temperature"
  t_dhw:
    id: dhw_temperature
    name: "Hot Water Temperature"
  t_dhw2:
    name: "Hot Water Temperature 2"

  rel_mod_level:
    id: rel_mod_level
    name: "Boiler Relative Modulation Level"
  t_outside:
    name: Outside Temperature
  t_ret:
    name: Return Water Temperature

  max_t_set:
    name: Max CH Setpoint    
  max_t_set_ub:
    name: Upper Bound of CH Setpoint    
  max_t_set_lb:  
    name: Lower Bound CH Setpoint
  t_exhaust:    
    name: Boiler Exhaust Temperature
    entity_category: diagnostic
  ch_pressure:    
    name: Water Pressure
    entity_category: diagnostic
  oem_fault_code:
    name: OEM Fault Code
    entity_category: diagnostic
  oem_diagnostic_code:
    name: OEM Diagnostic Code
    entity_category: diagnostic

# Use PID Climate component for automatic boiler setpoint calculation
# https://esphome.io/components/climate/pid
climate:
  - platform: pid
    id: ch_climate
    name: "Heating Climate"
    heat_output: ch_setpoint
    default_target_temperature: 22
    sensor: current_temperature
    visual:
      min_temperature: 15
      max_temperature: 30
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    control_parameters:
      kp: 0.5
      ki: 0.001
      kd: 0
    on_state:
      - if:
          condition:
          - lambda: 'return id(ch_climate).mode == CLIMATE_MODE_OFF;'
          then:
            - switch.turn_off: ch_enable
          else:
            - switch.turn_on: ch_enable
          
      - logger.log:
          format: "climate mode=%s, t=%.1f"
          args: ['std::string(LOG_STR_ARG(climate_mode_to_string(x.mode))).c_str()', 'x.target_temperature' ]            
          level: INFO
```

In the sat wizard
<img width="383" height="336" alt="image" src="https://github.com/user-attachments/assets/10a07f82-d307-4977-bc68-173cfb4450c4" />
<img width="469" height="553" alt="image" src="https://github.com/user-attachments/assets/9f0c9ae0-4610-4214-8eb0-3c975ef75a42" />
<img width="548" height="402" alt="image" src="https://github.com/user-attachments/assets/21b59570-4dd0-498e-89e4-84b23961b1e8" />
I have underfloor downstairs and radiators in the bedrooms upstairs.
<img width="548" height="697" alt="image" src="https://github.com/user-attachments/assets/5cac69e8-3ee2-4485-96c6-d5b3adeb6fe5" />

Clearly I'm doing something wrong.
