### ISSUE TITLE
Multi room heating 

### ISSUE THREAD

**Issue by ronaldt80** [Alexwijn/SAT#16]
Is my understanding correct that the error level related to the highest gap between room temp and target temp? Is it an idea to assign a weight to each room? For instance, my office has one small radiator, whilst the living room consist of 4 rather large ones. They now seem to be treated equally.

Also, would it be an option to allocate a third party temperature sensor? It is my experience that the built in sensor is way off. For instance, a zigbee sensor which is paired to the climate entity?

**Comment by enryIT** [comment]
I agree on the weight, that would be a nice feature for those who have very different radiators.

For the second part, I think you should be able to fix this problem by using a proxy entity, this is for example my configuration:
```
climate:
  - platform: generic_thermostat
    unique_id: studio_fixed
    name: Studio Fixed
    heater: input_boolean.studio_thermostat
    target_sensor: sensor.termoigrometro_studio_temperature
    min_temp: 5
    max_temp: 25
    ac_mode: false
    target_temp: 17
    cold_tolerance: 0
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    precision: 0.1
    target_temp_step: 0.5
    away_temp: 18
    comfort_temp: 21
    home_temp: 19
    sleep_temp: 17.5
[... other generic thermostats for each room ...]
```
where
`input_boolean.studio_thermostat` id the entity is of a HA boolean helper
`sensor.termoigrometro_studio_temperature` is the entity id of the external temperature sensor

Then you would use `climate.studio_fixed` as a secondary SAT climate entity.

Obviously you'll need an automation of some sort in order to open and close the single valve when the generic_thermostat starts or stops heating, something like this:

```
alias: TRV Studio
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.studio_fixed
    attribute: hvac_action
condition: []
action:
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: climate.studio_fixed
            attribute: hvac_action
            state: idle
          - condition: numeric_state
            entity_id: climate.studio
            attribute: temperature
            above: 12
    then:
      - service: climate.set_temperature
        data:
          temperature: 12
        target:
          entity_id: climate.studio
    else:
      - if:
          - condition: and
            conditions:
              - condition: state
                entity_id: climate.studio_fixed
                attribute: hvac_action
                state: heating
              - condition: numeric_state
                entity_id: climate.studio
                attribute: temperature
                below: 25
        then:
          - service: climate.set_temperature
            data:
              temperature: 25
            target:
              entity_id: climate.studio
mode: single
```
where `climate.studio_fixed` is the proxy entity and `climate.studio` is the real radiator valve climate entity.
