### ISSUE TITLE
Climate does not support action climate.turn_on.

### ISSUE THREAD

**Issue by convicte** [Alexwijn/SAT#78]
Not much more to say here, beyond the fact the SAT based climate entities do not accept `ON/OFF` or `toggle` commands, when default behavior on in a dashboard is triggered.

![image](https://github.com/user-attachments/assets/9c46eb6f-cad6-4e96-9234-59ce92b6ab41)

Pressing a dashboard element, the climate return the error `does not support action climate.turn_on.`

Card YAML for reference:

```yaml

type: custom:mushroom-climate-card
entity: climate.master_bedroom
show_temperature_control: true
collapsible_controls: true
icon: mdi:heating-coil
name: Floor heating
```
